version: "3.1"

services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: nodemon --inspect=0.0.0.0:9229 backend/server.js
    container_name: kubelive
    image: bwv988/kubelive
    ports:
      - "80:80"      
      - "9229:9229"
    volumes:
      - ./src/:/opt/app
      - notused:/opt/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
    notused:
